version: '3'

services:

    web:
        build: ./web
        restart: always
        environment:
            - APACHE_RUN_USER=#1000
            - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d/:/usr/local/etc/php/custom.d/
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - ./web/php-ini/:/usr/local/etc/php/custom.d/
        ports:
            - ${APP_HOST_PORT}:80
        working_dir: ${APP_PATH_CONTAINER}
#        networks:
#            - docker_network

    db:
        image: mysql:5.7.26
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql
        ports:
            - ${DB_HOST_PORT}:3306
#        networks:
#            - docker_network

    adminer:
        image: adminer
        restart: always
        ports:
            - ${ADMINER_HOST_PORT}:8080

    composer:
        image: composer:1.6
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: composer install

#networks:
#  default:
#    external:
#      name: docker_network

#networks:
#    docker_network:
#        driver: custom-driver-1

